name: Snyk Bug Scan

on: push

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install dependencies (required for accurate scan)
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # Run Snyk scan (only shows vulnerabilities)
      - name: Run Snyk scan for frontend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: ./frontend

      - name: Run Snyk scan for backend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: ./backend
